DATA_PATH = ./data
TAZ = $(DATA_PATH)/vci.taz.xml 
OD = $(DATA_PATH)/vci.od
TRIP = $(DATA_PATH)/vci.trips.xml
NET = $(DATA_PATH)/vci.net.xml
ROU = $(DATA_PATH)/vci.rou.xml
CONFIG = $(DATA_PATH)/vci.sumocfg

.PHONY: all data gen_od

all: gen_od_volume gen_routes calibration

# Generate the origin/destination matrix
gen_od_volume:
	@python -m src.generate_OD.gen_od_volume

# Generate the .rou.xml route files.
gen_routes:
	@python -m src.sumo.gen_route_map
	@python -m src.sumo.gen_routes
	@make repair_paths

data:
	@echo "Processing data..."
	@python -m src.dataProcessing.clean_real_data
	@python -m src.dataProcessing.clean_simulation_data
	@echo "Data processed!"

# Start the calibration of the VCI model
calibration: gen_od_volume
	@echo "Executing sumo..."
	@sumo $(CONFIG)
	@echo "Sumo executed!"
	@make data
	@python -m src.dataProcessing.calibration

# Fix the wrong paths generated by the gen_routes
repair_paths:
	@echo "Fixing paths..."
	@duarouter --net-file $(NET) --route-files $(ROU) --repair -o output
	@echo "Cleaning..."
	@rm $(ROU)
	@mv output $(ROU)
	@echo "Paths fixed!"

clean:
	@echo "Removing files..."
	@rm -f ./data/vci.trips.xml ./data/vci.taz.xml ./data/vci.od ./data/*.rou.xml ./data/*.rou.alt.xml 


# PROCESS_NET =======================================================================================================
# Creates the net from the osm, with only roads for passengers. This is the default vehicle class and denotes regular passenger traffic. 
# Vehicle types: https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html
# netconverter: https://sumo.dlr.de/docs/netconvert.html 
process_net: netconvert clean_net

netconvert:
	netconvert --osm ./data/vci.osm -o ./data/vci.net.xml --remove-edges.isolated true --remove-edges.by-vclass private,emergency,authority,army,vip,pedestrian,hov,coach,delivery,moped,bicycle,evehicle,tram,rail_urban,rail,rail_electric,rail_fast,ship

# Remove edges decoupled from the network and losing nodes
clean_net: 
	netconvert -s ./data/vci.net.xml -o ./data/porto_2.net.xml --remove-edges.isolated true 
